{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ template "nfs-client-provisioner.name" . }}
    chart: {{ template "nfs-client-provisioner.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "nfs-client-provisioner.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "nfs-client-provisioner.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "nfs-client-provisioner.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
