{{- if .Values.global.persistence.nfs.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "magento.fullname" . }}-volume
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{.Values.global.persistence.nfs.serverIp}}
    path: {{.Values.global.monolith.volumeHostPath}}
{{- end }}
